export const GET_CHARACTERS_REQUEST = 'GET_CHARACTERS_REQUEST';
export const GET_CHARACTERS_REQUEST_SUCCESS = 'GET_CHARACTERS_REQUEST_SUCCESS';
export const GET_CHARACTERS_REQUEST_ERROR = 'GET_CHARACTERS_REQUEST_ERROR';